### ISSUE TITLE
`gt.merge_tiles` method is not working as expected!

### ISSUE THREAD

**Issue by iamtekson** [osgeonepal/geotile#53]
In `merge_tiles` method, the current implementation doesn't merge the tiles and generate the correct merged file. Please rewrite the function to fix this bug.

**Comment by hillsonghimire** [comment]
I suspect the issue might be due to pixel bleeding a little outside the initial input data bounds.
![image](https://github.com/osgeonepal/geotile/assets/34327057/7d07d743-2c3f-44ca-a701-8a540f1b96e4)

**Potential solution:**
1. Equal padding the input on all side in tile generating step, so that the `width or height = (tile_size * stride_x or stride_y)`
2. After merging remove the extra padding.

![image](https://github.com/osgeonepal/geotile/assets/34327057/09f27751-f30d-466c-944d-5ea783c184d4)

**Comment by hillsonghimire** [comment]
```
k=-1
for j in range(y_gen):
    for i in range(x_gen):
        k=k+1
        z[i*stride_x:(i+1)*stride_x, j*stride_y:(j+1)*stride_y]=tile_dta[k]

// WRITE CODE TO UPDATE **height**, and **width** in **self.meta:**
// **width=new_width, height=new_height**, before using in block below:

with rasterio.open('output.tif', "w",  **self.meta) as outds:
        outds.write(z.astype('uint8'))

pyplot.imshow(z)
```

As suspected the issue is due to width and height not updated in the **self.meta before writing. I was able to regenerate the image with above modification. Also the performance was greatly improved by first reconstructing the numpy array from tile (since both doesn't have coordinate, it makes sense as well), then writing it on the file, instead of `for` loop in reading and writing operation, which is more resource intensive. 

![image](https://github.com/osgeonepal/geotile/assets/34327057/3035170d-e823-4793-aec1-a1330bf640e6)

**Comment by iamtekson** [comment]
For now, I am simply saving all the generated tiles into a new folder and mosaicing it by using `gt.mosaic()` function. Yes, you are right, we have some issues in `merge_tile` method and I feel like we need to rewrite the function. So, were you able to solve the issue? if yes, please send a PR.
